### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by amiltonwong** [halismai/bpvo#1]
Dear @halismai ,

I had followed your installation guide. I passed cmake step (log: https://gist.github.com/amiltonwong/d897a28251b4f67a69565745d7b16744)
However, I came across the following make error:

==============================================

root@milton-OptiPlex-9010:~/bpvo/build# make
Scanning dependencies of target bpvo
[  1%] Building CXX object bpvo/CMakeFiles/bpvo.dir/types.cc.o
c++: error: unrecognized command line option ‘-fdiagnostics-color=auto’
make[2]: *** [bpvo/CMakeFiles/bpvo.dir/types.cc.o] Error 1
make[1]: *** [bpvo/CMakeFiles/bpvo.dir/all] Error 2
make: *** [all] Error 2

==============================================

My g++ version is 4.8.4, could u suggest me how to fix it?

THX~

**Comment by amiltonwong** [comment]
Update:

I upgrade g++ into 4.9.3 version and fix the build problem

**Comment by halismai** [comment]
Thanks for reporting the issue. I've removed the flag in case you want to use g++4.8
