### ISSUE TITLE
question about vo_example.cc

### ISSUE THREAD

**Issue by amiltonwong** [halismai/bpvo#2]
Hi, @halismai ,

I had run  "vo_example" for simple example. However, no operation for useful output is implemented in vo_example.cc, it just pass the left images and depth images into vo. If I want to save the vo output into a text file, how should I modify the file [vo_example.cc](https://github.com/halismai/bpvo/blob/master/apps/vo_example.cc)?

THX~

**Comment by halismai** [comment]
Hi @amiltonwong 

Excellent questions. It depends on what you want to store. I've pushed an example that saves the trajectory for the camera in a coordinate frame with respect to the first call to addFrame. The example is in, vo_example_write_to_file.cc 

There are other information in the Result structure, such as the point cloud and other useful statistics. Look inside apps/vo_app.cc for how to store the point cloud if you want.

Hope that helps.

**Comment by amiltonwong** [comment]
Hi, @halismai ,
Thanks for your reply. Now I could get the [poses](https://gist.github.com/amiltonwong/eda34c5442e95ce5cb5be2247e6083fe) and [camera trajectories](https://gist.github.com/amiltonwong/c2a6280d1256370976d9a8d7ea492788) from "vo_example_write_to_file", I think the next step is how to display the trajectory compared with ground-truth such as plotting the Fig. 10 in your paper "Direct Visual Odometry using Bit-Planes". Any suggestions?

THX~

**Comment by halismai** [comment]
I've used matlab to plot the trajectory. In matlab you can do:

`>> load results_path.txt
>> plot3(results_path(:,1), results_path(:,2), results_path(:,3), 'k.-');
>> axis equal tight;`

The kitti data evaluation was done using the KITTI devset.  Ultimately, each dataset has its own evaluations system. I'd look at some of the available datasets with groundtruth and evaluate the system on the data most similar to the situations you are targeting. Some datasets includes:

- http://vision.in.tum.de/data/datasets/rgbd-dataset
- http://corbs.dfki.uni-kl.de/
- http://www.cvlibs.net/datasets/kitti/
- http://www.doc.ic.ac.uk/~ahanda/VaFRIC/iclnuim.html
- http://www.robots.ox.ac.uk/NewCollegeData/
- http://www.mrpt.org/robotics_datasets

HTH

**Comment by amiltonwong** [comment]
Hi, @halismai ,
Thanks for your reply and suggestions. One question is: For KITTI dataset, there are a lot of sequences for VO task / Stereo task. which sequence have you tried in your previous experiment? And which sequence refer to the one in Fig 17 in your paper "Direct Visual Odometry using Bit-Planes" ?

THX~

**Comment by amiltonwong** [comment]
Hi, @halismai ,
One more question, the groundtruth for NewTsukubaStereoDataset is [here](https://gist.github.com/amiltonwong/c1503bbc82f54b45b5dd5807ee113675). The left three columns refers to XYZ corrdinate in camera trajectory. However , these groundtruth values look significantly different to the bpvo output : [result_path.txt](https://gist.github.com/amiltonwong/c2a6280d1256370976d9a8d7ea492788)

**Comment by halismai** [comment]
Hi @amiltonwong 

As for the NewTsukubaDataset, bpvo will return the path in meters. The groundtruth path from Tsukuba I believe is in centimeters.

For KITTI, Fig. 13 includes the performance over all training sequences using the KITTI devkit. Fig. 17 shows a reconstruction example from the first few frames of sequence 0

**Comment by halismai** [comment]
Also, for NewTsukuba the coordinate systems are different. My coordinate convention is the one commonly used in computer vision, where it is right-handed with Z increasing forward, Y increasing downward and X to the right. NewTsukuba data has a different coordinate convention. So, you'll have to perform a coordinate transform before performing a quantitative analysis.
