### ISSUE TITLE
MAD Scale Estimator

### ISSUE THREAD

**Issue by inspirit** [halismai/bpvo#3]
Hi,
can you please explain why the MAD scale estimator differs from PTAM and other implementations here:
https://github.com/halismai/bpvo/blob/master/bpvo/mestimator.cc#L464
```
(1.4826f * (1.0f + 5.0f / (buffer.size()-6) )) * median(buffer);
```
you are using ```buffer.size() - 6``` while in other implementation i see ```buffer.size()*2 - 6```

**Comment by halismai** [comment]
Hi @inspirit 

Last time I looked at PTAM was a few years ago and do not remember the details fully.

I was following the excellent write up here http://research.microsoft.com/en-us/um/people/zhang/Papers/ZhangIVC-97-01.pdf look at Equation 27. See also Eq. 4 here https://www.eecs.berkeley.edu/~yang/courses/cs294-6/papers/Steward_Robust%20parameter%20estimation%20in%20computer%20vision.pdf

If 'n' is the number of points and 'p' is the parameter vector size, then the correction factor is 5 / (n-p)

In either case, this correction factor is only useful for small 'n'. For large 'n', e.g. n = 1000, the factor is approx 0.005, the number of points we usually work with is on the order of n = 10000 which results in a factor of 0.0005

**Comment by inspirit** [comment]
i see. seems like lots of other impl such as SVO, DVS and some more just copied it from PTAM :)
thanx for the links!
